export interface RoadmapPhase {
  name: string;
  range: [number, number];
  detail: string;
}

export interface RoadmapWeek {
  week: number;
  title: string;
  objective: string;
  topics: string[];
  deliverable: string;
  resourceIds: string[];
}

export interface LearningResource {
  id: string;
  title: string;
  provider: string;
  platform: string;
  category: string;
  topics: string[];
  weeks: number[];
  description: string;
  url: string;
  access: "Free" | "Freemium";
}

export const phases: RoadmapPhase[] = [
  {
    name: "Coding Fundamentals",
    range: [1, 4],
    detail: "Build a steady Python foundation and write a small, complete program.",
  },
  {
    name: "Data Structures & Algorithms",
    range: [5, 12],
    detail: "Learn the common data structures and solve problems with clear reasoning.",
  },
  {
    name: "SQL + DBMS",
    range: [13, 16],
    detail: "Query relational data, understand database design, and practice deliberately.",
  },
  {
    name: "Core CS",
    range: [17, 22],
    detail: "Review operating systems, networking, OOP, software engineering, and DBMS.",
  },
  {
    name: "Cybersecurity + Cloud Security",
    range: [23, 28],
    detail: "Connect security principles with hands-on web, network, and cloud practice.",
  },
  {
    name: "Projects + Resume",
    range: [29, 32],
    detail: "Build two explainable projects and turn the work into a clear portfolio story.",
  },
  {
    name: "GenC Next Intensive",
    range: [33, 36],
    detail: "Practice timed coding, SQL, aptitude, and full assessment sets.",
  },
  {
    name: "Interview",
    range: [37, 40],
    detail: "Prepare technical and behavioral answers, then complete the final readiness review.",
  },
];

export const roadmapWeeks: RoadmapWeek[] = [
  {
    week: 1,
    title: "Python setup, variables & input/output",
    objective: "Set up Python and turn simple problem statements into small working programs.",
    topics: [
      "Install Python and choose an editor; run a first script",
      "Variables, naming, comments, and basic debugging",
      "Numbers, strings, booleans, and type conversion",
      "Input, output, and formatted strings",
      "Arithmetic, comparison, and logical operators",
      "Write 10 small programs and note the input, output, and edge cases",
    ],
    deliverable: "A folder of 10 runnable Python basics programs with a short README.",
    resourceIds: ["python-tutorial", "cs50p"],
  },
  {
    week: 2,
    title: "Conditionals, loops & patterns",
    objective: "Use branching and repetition to express logic without duplicating code.",
    topics: [
      "if, elif, else, and nested conditions",
      "Truthiness, comparisons, and compound logical conditions",
      "for loops, range, and iterating over sequences",
      "while loops, counters, and safe stopping conditions",
      "break, continue, and loop tracing",
      "Print number and character patterns; explain each loop invariant",
    ],
    deliverable: "A set of 8 loop and pattern exercises with sample inputs and outputs.",
    resourceIds: ["freecodecamp-python", "programiz-python", "gfg-python"],
  },
  {
    week: 3,
    title: "Strings, lists & tuples",
    objective: "Manipulate ordered data and select the right operation for common tasks.",
    topics: [
      "String indexing, slicing, immutability, and common methods",
      "List creation, indexing, slicing, and mutation",
      "Looping over lists and building a result list",
      "Tuples, unpacking, and when immutable data is useful",
      "Search, count, min/max, and basic sorting",
      "Practice reverse, palindrome, frequency, and duplicate-removal tasks",
    ],
    deliverable: "A small text/list utility module with at least 6 tested functions.",
    resourceIds: ["gfg-python", "leetcode-study"],
  },
  {
    week: 4,
    title: "Functions, files, OOP & a mini project",
    objective: "Organize Python code into reusable functions and build a small command-line tool.",
    topics: [
      "Functions, parameters, return values, scope, and docstrings",
      "Modules, imports, and splitting a program into files",
      "Read and write text and CSV files safely",
      "Classes, objects, constructors, and encapsulation basics",
      "Exceptions, validation, and useful error messages",
      "Dictionaries, sets, and choosing a collection",
      "Build a command-line expense tracker or contact book",
    ],
    deliverable: "A file-backed command-line mini project with input validation and README.",
    resourceIds: ["python-tutorial", "cs50p"],
  },
  {
    week: 5,
    title: "Big-O, arrays & complexity",
    objective: "Estimate time and space costs before choosing an implementation.",
    topics: [
      "Big-O, Big-Theta, and Big-Omega intuition",
      "Constant, logarithmic, linear, and quadratic growth",
      "Best, average, and worst-case analysis",
      "Array traversal, insertion, deletion, and search",
      "Prefix sums and in-place updates",
      "Solve 8 array problems and state the complexity of each",
    ],
    deliverable: "Eight solved array problems with a one-line complexity note for each.",
    resourceIds: ["gfg-dsa", "leetcode-study", "visualgo"],
  },
  {
    week: 6,
    title: "Strings, hashing & frequency maps",
    objective: "Use string operations and hash-based lookup to solve common interview problems.",
    topics: [
      "String traversal and character encoding basics",
      "Hash maps and sets: average lookup and update cost",
      "Frequency counting and grouping",
      "Anagrams, first unique character, and duplicate detection",
      "Two-sum and complementary lookup",
      "Solve 8 string and hashing problems",
    ],
    deliverable: "Eight solved string/hash-map problems, including an anagram checker.",
    resourceIds: ["gfg-dsa", "leetcode-study", "visualgo"],
  },
  {
    week: 7,
    title: "Linked lists, stacks & queues",
    objective: "Understand pointer-based lists and use stacks and queues for ordered work.",
    topics: [
      "Singly linked-list nodes and traversal",
      "Insert, delete, search, and reverse a linked list",
      "Stack operations and balanced-bracket checking",
      "Queue and deque operations",
      "Use cases: undo, scheduling, and breadth-first processing",
      "Solve linked-list, stack, and queue practice problems",
    ],
    deliverable: "Working linked-list, stack, and queue implementations plus 6 practice solutions.",
    resourceIds: ["gfg-dsa", "leetcode-study"],
  },
  {
    week: 8,
    title: "Recursion & backtracking",
    objective: "Trace recursive calls and use backtracking to explore constrained choices.",
    topics: [
      "Base cases, recursive cases, and call-stack tracing",
      "Recursion on arrays and strings",
      "Subsets and permutations",
      "Backtracking state, choices, and undo steps",
      "Pruning invalid branches",
      "Solve recursion and backtracking exercises",
    ],
    deliverable: "A call-tree explanation and 5 working recursion/backtracking solutions.",
    resourceIds: ["gfg-dsa", "leetcode-study"],
  },
  {
    week: 9,
    title: "Trees, BSTs & traversals",
    objective: "Represent hierarchical data and choose the right tree traversal.",
    topics: [
      "Tree terminology and binary-tree representation",
      "Preorder, inorder, and postorder traversals",
      "Level-order traversal with a queue",
      "Binary search tree search, insert, and delete concepts",
      "Height, depth, and balanced-tree intuition",
      "Solve tree traversal and BST problems",
    ],
    deliverable: "A visual traversal trace and 6 solved binary-tree/BST problems.",
    resourceIds: ["gfg-dsa", "visualgo", "leetcode-study"],
  },
  {
    week: 10,
    title: "Heaps & priority queues",
    objective: "Use heap operations to keep track of the highest- or lowest-priority item.",
    topics: [
      "Min-heaps, max-heaps, and the heap property",
      "Insert, peek, remove, and heapify",
      "Priority queue use cases",
      "Top-K and Kth-largest patterns",
      "Merge sorted sequences with a heap",
      "Solve heap and priority-queue practice problems",
    ],
    deliverable: "A priority-queue exercise set and 5 solved heap problems.",
    resourceIds: ["gfg-dsa", "leetcode-study"],
  },
  {
    week: 11,
    title: "Graphs, BFS & DFS",
    objective: "Model relationships as graphs and traverse them safely.",
    topics: [
      "Vertices, edges, directed/undirected, and weighted graphs",
      "Adjacency lists and adjacency matrices",
      "Breadth-first search and visited sets",
      "Depth-first search with recursion and an explicit stack",
      "Connected components and path detection",
      "Solve graph traversal problems and state their complexity",
    ],
    deliverable: "BFS and DFS implementations with 5 solved graph problems.",
    resourceIds: ["gfg-dsa", "leetcode-study", "visualgo"],
  },
  {
    week: 12,
    title: "Sorting, searching & greedy patterns",
    objective: "Select standard sorting/searching patterns and recognize simple greedy choices.",
    topics: [
      "Linear and binary search; sorted-input requirements",
      "Merge sort and quicksort at a conceptual level",
      "Stable sorting and comparator functions",
      "Two pointers and sliding window",
      "Greedy choices, intervals, and counterexamples",
      "Complete a timed mixed DSA set and review mistakes",
    ],
    deliverable: "A timed mixed DSA set with error notes and a complexity summary.",
    resourceIds: ["gfg-dsa", "leetcode-study"],
  },
  {
    week: 13,
    title: "Relational databases & SQL basics",
    objective: "Read a relational schema and write clear single-table queries.",
    topics: [
      "Tables, rows, columns, schemas, and data types",
      "Primary keys, foreign keys, and relationships",
      "SELECT, aliases, and DISTINCT",
      "WHERE filters, comparison operators, and NULL",
      "ORDER BY, LIMIT, and result inspection",
      "Practice SELECT and filtering questions",
    ],
    deliverable: "A SQL notebook with 20 SELECT, filtering, and sorting queries.",
    resourceIds: ["sqlbolt", "sqlzoo"],
  },
  {
    week: 14,
    title: "Joins, aggregation & subqueries",
    objective: "Combine related data and summarize it without changing the intended grain.",
    topics: [
      "INNER JOIN and LEFT JOIN",
      "Join keys, duplicate rows, and table aliases",
      "COUNT, SUM, AVG, MIN, and MAX",
      "GROUP BY and HAVING",
      "Scalar and correlated subqueries",
      "Solve multi-table reporting questions",
    ],
    deliverable: "Twenty join and aggregation queries with expected result reasoning.",
    resourceIds: ["sqlbolt", "sqlzoo"],
  },
  {
    week: 15,
    title: "Database design, normalization & transactions",
    objective: "Explain relational design trade-offs and protect data consistency.",
    topics: [
      "Functional dependencies and normalization through 3NF",
      "Constraints, defaults, and referential integrity",
      "Indexes and the read/write trade-off",
      "Views and stored procedure concepts",
      "Transactions, ACID, COMMIT, and ROLLBACK",
      "Practice schema design and transaction scenarios",
    ],
    deliverable: "A normalized schema sketch with keys, constraints, and one transaction flow.",
    resourceIds: ["neso-dbms", "gate-smashers"],
  },
  {
    week: 16,
    title: "SQL interview practice: 100 queries",
    objective: "Build speed and accuracy across common SQL query patterns.",
    topics: [
      "Complete a 100-query practice plan in manageable sets",
      "Mix filters, joins, aggregates, and subqueries",
      "Use window functions for ranking and running totals",
      "Review NULL handling, duplicates, and grouping errors",
      "Take a timed SQL set and record weak patterns",
    ],
    deliverable: "A completed 100-query log with dates, accuracy, and three review topics.",
    resourceIds: ["leetcode-sql", "hackerrank-sql"],
  },
  {
    week: 17,
    title: "Operating systems: processes & scheduling",
    objective: "Explain how an operating system runs and schedules work.",
    topics: [
      "Kernel, user mode, system calls, and process lifecycle",
      "Processes versus threads",
      "CPU scheduling goals and common algorithms",
      "Context switching and concurrency basics",
      "Concurrency risks and race conditions",
      "Practice short OS interview explanations",
    ],
    deliverable: "A one-page OS summary with process/thread and scheduling comparisons.",
    resourceIds: ["gfg-os", "neso-os"],
  },
  {
    week: 18,
    title: "Memory management, synchronization & deadlocks",
    objective: "Connect memory allocation and synchronization concepts to practical symptoms.",
    topics: [
      "Stack, heap, and virtual memory",
      "Paging, segmentation, and page replacement",
      "Critical sections, mutexes, and semaphores",
      "Deadlock conditions and prevention",
      "Race conditions and synchronization examples",
      "Review common OS interview questions",
    ],
    deliverable: "A memory/synchronization concept map and 15 answered OS questions.",
    resourceIds: ["gfg-os", "neso-os"],
  },
  {
    week: 19,
    title: "Computer networks & web protocols",
    objective: "Trace what happens when a client connects to a network service.",
    topics: [
      "OSI and TCP/IP models",
      "IP addresses, subnets, and ports",
      "TCP versus UDP and connection setup",
      "DNS, DHCP, and routing basics",
      "HTTP/HTTPS request-response flow and status codes",
      "Practice network troubleshooting scenarios",
    ],
    deliverable: "A labeled request-flow diagram from URL entry to HTTPS response.",
    resourceIds: ["gfg-networks", "practical-networking"],
  },
  {
    week: 20,
    title: "OOP & Java fundamentals",
    objective: "Explain object-oriented design and refresh a common interview language.",
    topics: [
      "Encapsulation, abstraction, inheritance, and polymorphism",
      "Interfaces, classes, constructors, and access modifiers",
      "Java types, control flow, and methods",
      "Collections and exception handling",
      "Composition versus inheritance",
      "Practice explaining an OOP design with a small example",
    ],
    deliverable: "A small Java OOP example with a class diagram and explanation.",
    resourceIds: ["neso-oop", "gate-smashers", "java-tutorial"],
  },
  {
    week: 21,
    title: "Software engineering, Git & testing",
    objective: "Show that you can work in a repeatable, reviewable development process.",
    topics: [
      "SDLC, requirements, and iterative development",
      "Git commits, branches, merges, and conflict resolution",
      "Unit, integration, and system testing",
      "Readable code, naming, and refactoring",
      "Issue tracking and pull-request review",
      "Create a clean repository history for a practice project",
    ],
    deliverable: "A GitHub repository with a clear README, tests, and meaningful commits.",
    resourceIds: ["gfg-software", "github-skills"],
  },
  {
    week: 22,
    title: "Core CS revision & technical check",
    objective: "Practice connecting OS, networks, databases, and OOP in interview answers.",
    topics: [
      "Review OS processes, memory, and synchronization",
      "Review networks, DNS, HTTP, TCP, and common ports",
      "Review DBMS keys, normalization, indexes, and ACID",
      "Review OOP pillars and Java fundamentals",
      "Take a mixed Core CS mock and classify missed questions",
    ],
    deliverable: "A timed Core CS mock with an error log and concise correction notes.",
    resourceIds: ["gfg-os", "gfg-networks", "neso-dbms"],
  },
  {
    week: 23,
    title: "Security principles & threat modeling",
    objective: "Use security vocabulary to reason about assets, threats, and controls.",
    topics: [
      "Confidentiality, integrity, and availability",
      "Authentication, authorization, and accounting",
      "Assets, threat actors, attack surfaces, and risk",
      "Least privilege, defense in depth, and secure defaults",
      "Basic threat-modeling steps and trust boundaries",
      "Walk through one threat model for a student web app",
    ],
    deliverable: "A simple threat model with assets, threats, likelihood, and mitigations.",
    resourceIds: ["cisco-cyber", "tryhackme-presecurity"],
  },
  {
    week: 24,
    title: "Networking security foundations",
    objective: "Recognize common network controls and read a basic packet capture.",
    topics: [
      "Common ports and service exposure",
      "Firewalls, security groups, and network segmentation",
      "IDS versus IPS and alert context",
      "TLS purpose and certificate basics",
      "Wireshark capture filters and safe packet inspection",
      "Map a small network and identify its trust boundaries",
    ],
    deliverable: "A network diagram with zones, ports, controls, and a short capture analysis.",
    resourceIds: ["practical-networking", "cisco-cyber"],
  },
  {
    week: 25,
    title: "Web application security & OWASP Top 10",
    objective: "Understand common web risks and practice mitigations in authorized labs.",
    topics: [
      "OWASP Top 10 overview and secure development",
      "Injection and parameterized queries",
      "Cross-site scripting and output encoding",
      "Authentication, session, and access-control failures",
      "CSRF, security headers, and input validation",
      "Complete beginner web-security labs in an authorized environment",
    ],
    deliverable: "A lab journal connecting each tested vulnerability to a defensive fix.",
    resourceIds: ["owasp-top10", "portswigger-academy", "tryhackme-web"],
  },
  {
    week: 26,
    title: "Cryptography, IAM & access control",
    objective: "Choose appropriate cryptographic and identity controls for common scenarios.",
    topics: [
      "Symmetric and asymmetric encryption",
      "Hashing, salting, and password storage",
      "Digital signatures, certificates, and PKI",
      "MFA, authorization models, and access reviews",
      "Key management, rotation, and safe handling",
      "Explain when to encrypt, hash, or sign data",
    ],
    deliverable: "A comparison sheet for encryption, hashing, signatures, and IAM controls.",
    resourceIds: ["crypto101", "neso-crypto", "cisco-cyber"],
  },
  {
    week: 27,
    title: "Incident response, logging & risk",
    objective: "Describe how teams detect, assess, contain, and learn from an incident.",
    topics: [
      "Preparation, detection, analysis, containment, eradication, recovery",
      "Log sources, timestamps, and event context",
      "SIEM concepts, alert triage, and false positives",
      "Evidence handling and incident notes",
      "Risk likelihood, impact, and treatment",
      "Practice a short incident-response tabletop scenario",
    ],
    deliverable: "An incident timeline and response checklist for a sample account compromise.",
    resourceIds: ["tryhackme-soc", "cisco-cyber"],
  },
  {
    week: 28,
    title: "Cloud security foundations",
    objective: "Apply shared responsibility and least privilege to a cloud workload.",
    topics: [
      "Cloud service models and shared responsibility",
      "Cloud IAM roles, policies, and least privilege",
      "Network controls and private service access",
      "Secure storage, encryption, and public-access prevention",
      "Logging, monitoring, and security posture basics",
      "Compare security controls in AWS and Azure",
    ],
    deliverable: "A cloud security checklist for identity, network, storage, and logging.",
    resourceIds: ["aws-security", "azure-security"],
  },
  {
    week: 29,
    title: "Project 1: Password Strength Checker",
    objective: "Design a small security-focused utility that gives useful password feedback.",
    topics: [
      "Define user stories, scope, and safe handling requirements",
      "Threat model inputs, logs, storage, and privacy",
      "Choose strength rules and user-facing feedback",
      "Sketch the CLI or GUI flow and project structure",
      "Plan test cases for edge cases and common passwords",
    ],
    deliverable: "A project plan, threat model, UI sketch, and test checklist.",
    resourceIds: ["python-tutorial", "github-skills"],
  },
  {
    week: 30,
    title: "Build & document the Password Strength Checker",
    objective: "Complete, test, and explain the first portfolio project.",
    topics: [
      "Implement validation and transparent strength scoring",
      "Use safe test data; never store entered passwords",
      "Add clear feedback and accessibility-minded labels",
      "Test short, long, common, and mixed-character inputs",
      "Write setup instructions, limitations, and screenshots",
      "Prepare a concise project explanation and trade-offs",
    ],
    deliverable: "A tested Password Strength Checker with README and a short demo.",
    resourceIds: ["python-tutorial", "github-skills", "markdown-guide"],
  },
  {
    week: 31,
    title: "Project 2: Cloud Security Monitoring System",
    objective: "Design a practical monitoring workflow around cloud security signals.",
    topics: [
      "Define the project scope and simulated cloud environment",
      "Select identity, storage, and network events to monitor",
      "Sketch an architecture and data flow",
      "Define alert conditions and severity levels",
      "Plan access controls, retention, and privacy",
      "Create a small synthetic-event test set",
    ],
    deliverable: "An architecture diagram, event schema, and monitoring requirements.",
    resourceIds: ["aws-security", "azure-security", "github-skills"],
  },
  {
    week: 32,
    title: "Build, present & add both projects to your resume",
    objective: "Present both projects clearly, honestly, and with evidence of testing.",
    topics: [
      "Build a monitoring dashboard or alert workflow using safe sample data",
      "Test expected and unexpected event scenarios",
      "Document architecture, controls, and known limitations",
      "Add setup steps and a short demo to the repository",
      "Write impact-focused, truthful resume bullets for both projects",
      "Update GitHub profile and portfolio links",
    ],
    deliverable: "Two polished repositories, project demo notes, and updated resume bullets.",
    resourceIds: ["aws-security", "azure-security", "github-skills", "markdown-guide"],
  },
  {
    week: 33,
    title: "Advanced coding & timed DSA practice",
    objective: "Solve mixed coding questions under a time limit and explain the approach.",
    topics: [
      "Revisit arrays, strings, hashing, and two pointers",
      "Practice trees, graphs, recursion, and heaps",
      "State a brute-force approach before optimizing",
      "Write edge cases before coding",
      "Complete two timed coding sets and review mistakes",
    ],
    deliverable: "Two timed coding sets with time, score, and a categorized error log.",
    resourceIds: ["leetcode-study", "hackerrank"],
  },
  {
    week: 34,
    title: "SQL speed & query accuracy",
    objective: "Write common SQL query patterns quickly and validate the result grain.",
    topics: [
      "Review joins, grouping, HAVING, and subqueries",
      "Practice ranking and window functions",
      "Check duplicates, NULL behavior, and join cardinality",
      "Complete a timed SQL drill",
      "Review missed queries and redo them without hints",
    ],
    deliverable: "A timed SQL set with corrected solutions and a list of recurring mistakes.",
    resourceIds: ["leetcode-sql", "hackerrank-sql", "sqlbolt"],
  },
  {
    week: 35,
    title: "Aptitude, reasoning & communication",
    objective: "Practice placement-style numerical, logical, and verbal questions.",
    topics: [
      "Percentages, ratios, averages, and proportions",
      "Time, work, speed, distance, and basic probability",
      "Sequences, arrangements, and logical deductions",
      "Reading comprehension and grammar fundamentals",
      "Practice explaining the steps behind an answer",
    ],
    deliverable: "A mixed aptitude set with accuracy by topic and reviewed solutions.",
    resourceIds: ["indiabix"],
  },
  {
    week: 36,
    title: "GenC Next full assessment simulation",
    objective: "Practice switching between coding, SQL, aptitude, and technical questions.",
    topics: [
      "Complete a timed mixed assessment without interruptions",
      "Track accuracy and time by section",
      "Review questions that were guessed or skipped",
      "Revisit the two weakest technical topics",
      "Set a final four-week improvement plan",
    ],
    deliverable: "A full assessment result and a prioritized review plan for interview month.",
    resourceIds: ["hackerrank", "leetcode-study", "indiabix"],
  },
  {
    week: 37,
    title: "HR & behavioral interview answers",
    objective: "Prepare honest, specific answers about your background and motivation.",
    topics: [
      "Tell me about yourself: a concise 60–90 second introduction",
      "Why Cognizant and why GenC Next?",
      "Why cybersecurity and cloud security?",
      "Strengths, growth areas, and learning habits",
      "Behavioral examples using situation, action, and outcome",
      "Practice aloud and refine answers for clarity",
    ],
    deliverable: "A recorded practice introduction and 5 concise behavioral answer outlines.",
    resourceIds: ["cognizant-careers", "markdown-guide"],
  },
  {
    week: 38,
    title: "Technical interview review",
    objective: "Explain core concepts clearly and answer follow-up questions with examples.",
    topics: [
      "Review Python fundamentals, OOP, and collections",
      "Review DSA patterns and complexity",
      "Review SQL, DBMS, joins, and transactions",
      "Review OS and networking fundamentals",
      "Practice a technical Q&A session and identify gaps",
    ],
    deliverable: "A technical interview question bank with brief, accurate answer notes.",
    resourceIds: ["gfg-dsa", "gfg-os", "gfg-networks", "sqlbolt"],
  },
  {
    week: 39,
    title: "Cybersecurity, cloud & project interviews",
    objective: "Explain security decisions and defend project choices with evidence.",
    topics: [
      "Explain CIA, least privilege, and threat modeling",
      "Review OWASP risks and defensive controls",
      "Explain shared responsibility, IAM, and cloud logging",
      "Walk through both project architectures and trade-offs",
      "Practice a scenario-based incident or cloud-risk discussion",
    ],
    deliverable: "Two project walkthroughs and a security/cloud scenario practice record.",
    resourceIds: ["owasp-top10", "aws-security", "azure-security", "cognizant-careers"],
  },
  {
    week: 40,
    title: "Final mock interview & readiness checklist",
    objective: "Check every preparation area and finish with a clear, confident interview routine.",
    topics: [
      "Complete one full technical and HR mock interview",
      "Resume: accurate skills, project links, and measurable evidence",
      "GitHub/portfolio: working links, readable READMEs, and no secrets",
      "Coding and SQL: redo the highest-priority weak patterns",
      "Cybersecurity and cloud: review project and scenario explanations",
      "Interview logistics: documents, communication, and questions to ask",
      "Mark final checklist items only when they are ready",
    ],
    deliverable: "A completed final-readiness checklist and a one-page interview-day plan.",
    resourceIds: ["cognizant-careers", "leetcode-study", "hackerrank-sql"],
  },
];

export const learningResources: LearningResource[] = [
  {
    id: "python-tutorial",
    title: "Python Tutorial",
    provider: "Python Software Foundation",
    platform: "Official documentation",
    category: "Python",
    topics: ["Python", "fundamentals", "functions", "files", "OOP"],
    weeks: [1, 4, 29, 30],
    description: "Official Python language tutorial and reference.",
    url: "https://docs.python.org/3/tutorial/",
    access: "Free",
  },
  {
    id: "cs50p",
    title: "CS50’s Introduction to Programming with Python",
    provider: "Harvard University",
    platform: "Course",
    category: "Python",
    topics: ["Python", "fundamentals", "functions", "practice"],
    weeks: [1, 2, 4],
    description: "A structured introduction with lectures and programming exercises.",
    url: "https://cs50.harvard.edu/python/",
    access: "Free",
  },
  {
    id: "freecodecamp-python",
    title: "Scientific Computing with Python",
    provider: "freeCodeCamp",
    platform: "Course",
    category: "Python",
    topics: ["Python", "loops", "functions", "practice"],
    weeks: [2],
    description: "Free guided Python curriculum with hands-on projects.",
    url: "https://www.freecodecamp.org/learn/scientific-computing-with-python/",
    access: "Free",
  },
  {
    id: "programiz-python",
    title: "Python Tutorials",
    provider: "Programiz",
    platform: "Tutorial",
    category: "Python",
    topics: ["Python", "fundamentals", "loops"],
    weeks: [2],
    description: "Topic-by-topic Python explanations and examples.",
    url: "https://www.programiz.com/python-programming",
    access: "Free",
  },
  {
    id: "gfg-python",
    title: "Python Programming Tutorials",
    provider: "GeeksforGeeks",
    platform: "Tutorial",
    category: "Python",
    topics: ["Python", "strings", "lists", "practice"],
    weeks: [2, 3],
    description: "Python concept explanations with practice examples.",
    url: "https://www.geeksforgeeks.org/python/python-programming-language-tutorial/",
    access: "Free",
  },
  {
    id: "gfg-dsa",
    title: "DSA Tutorial",
    provider: "GeeksforGeeks",
    platform: "Tutorial",
    category: "DSA",
    topics: ["arrays", "hashing", "linked lists", "recursion", "trees", "heaps", "graphs", "sorting", "searching"],
    weeks: [5, 6, 7, 8, 9, 10, 11, 12, 33, 38],
    description: "Data structures and algorithms explanations and practice guides.",
    url: "https://www.geeksforgeeks.org/data-structures/",
    access: "Free",
  },
  {
    id: "leetcode-study",
    title: "LeetCode Study Plans",
    provider: "LeetCode",
    platform: "Practice platform",
    category: "DSA",
    topics: ["arrays", "strings", "hashing", "trees", "graphs", "timed practice"],
    weeks: [3, 5, 6, 7, 8, 9, 10, 11, 12, 33, 36, 38, 40],
    description: "Guided coding practice and interview-oriented problems.",
    url: "https://leetcode.com/studyplan/",
    access: "Freemium",
  },
  {
    id: "visualgo",
    title: "VisuAlgo",
    provider: "National University of Singapore",
    platform: "Visualizer",
    category: "DSA",
    topics: ["arrays", "trees", "graphs", "sorting", "data structures"],
    weeks: [5, 6, 9, 11],
    description: "Interactive visualizations of common data structures and algorithms.",
    url: "https://visualgo.net/en",
    access: "Free",
  },
  {
    id: "hackerrank",
    title: "Prepare for your coding interview",
    provider: "HackerRank",
    platform: "Practice platform",
    category: "Coding",
    topics: ["coding", "timed practice", "problem solving"],
    weeks: [33, 36],
    description: "Practice problems and interview-preparation kits.",
    url: "https://www.hackerrank.com/interview/interview-preparation-kit",
    access: "Free",
  },
  {
    id: "sqlbolt",
    title: "SQLBolt",
    provider: "SQLBolt",
    platform: "Interactive tutorial",
    category: "SQL",
    topics: ["SQL", "SELECT", "filters", "joins", "aggregation"],
    weeks: [13, 14, 34, 38],
    description: "Interactive lessons and exercises in SQL fundamentals.",
    url: "https://sqlbolt.com/",
    access: "Free",
  },
  {
    id: "sqlzoo",
    title: "SQL Tutorial",
    provider: "SQLZoo",
    platform: "Interactive tutorial",
    category: "SQL",
    topics: ["SQL", "SELECT", "joins", "aggregation"],
    weeks: [13, 14],
    description: "Interactive SQL practice from introductory queries through joins.",
    url: "https://sqlzoo.net/wiki/SQL_Tutorial",
    access: "Free",
  },
  {
    id: "neso-dbms",
    title: "DBMS video lectures",
    provider: "Neso Academy",
    platform: "Video lessons",
    category: "DBMS",
    topics: ["DBMS", "normalization", "transactions", "indexes"],
    weeks: [15, 22],
    description: "Video lessons covering common database-management concepts.",
    url: "https://www.youtube.com/@NesoAcademy",
    access: "Free",
  },
  {
    id: "gate-smashers",
    title: "DBMS and OOP lectures",
    provider: "Gate Smashers",
    platform: "Video lessons",
    category: "DBMS",
    topics: ["DBMS", "OOP", "Java"],
    weeks: [15, 20],
    description: "Topic-based CS and database video lessons.",
    url: "https://www.youtube.com/@GateSmashers",
    access: "Free",
  },
  {
    id: "leetcode-sql",
    title: "SQL 50 Study Plan",
    provider: "LeetCode",
    platform: "Practice platform",
    category: "SQL",
    topics: ["SQL", "joins", "aggregations", "interview practice"],
    weeks: [16, 34],
    description: "A focused SQL practice plan for interview-style queries.",
    url: "https://leetcode.com/studyplan/top-sql-50/",
    access: "Freemium",
  },
  {
    id: "hackerrank-sql",
    title: "SQL Practice",
    provider: "HackerRank",
    platform: "Practice platform",
    category: "SQL",
    topics: ["SQL", "query practice", "timed practice"],
    weeks: [16, 34, 40],
    description: "SQL exercises spanning basic selection through advanced queries.",
    url: "https://www.hackerrank.com/domains/sql",
    access: "Free",
  },
  {
    id: "gfg-os",
    title: "Operating Systems",
    provider: "GeeksforGeeks",
    platform: "Tutorial",
    category: "Core CS",
    topics: ["OS", "processes", "memory", "scheduling", "deadlocks"],
    weeks: [17, 18, 22, 38],
    description: "Operating-systems concepts and interview preparation.",
    url: "https://www.geeksforgeeks.org/operating-systems/",
    access: "Free",
  },
  {
    id: "neso-os",
    title: "Operating Systems video lectures",
    provider: "Neso Academy",
    platform: "Video lessons",
    category: "Core CS",
    topics: ["OS", "processes", "memory", "synchronization"],
    weeks: [17, 18],
    description: "Video lectures for operating-systems fundamentals.",
    url: "https://www.youtube.com/@NesoAcademy",
    access: "Free",
  },
  {
    id: "gfg-networks",
    title: "Computer Networks",
    provider: "GeeksforGeeks",
    platform: "Tutorial",
    category: "Networking",
    topics: ["networks", "TCP/IP", "DNS", "HTTP", "ports"],
    weeks: [19, 22, 38],
    description: "Computer-network fundamentals and interview questions.",
    url: "https://www.geeksforgeeks.org/computer-networks/",
    access: "Free",
  },
  {
    id: "practical-networking",
    title: "Networking Fundamentals",
    provider: "Practical Networking",
    platform: "Tutorial",
    category: "Networking",
    topics: ["networks", "routing", "subnets", "security"],
    weeks: [19, 24],
    description: "Practical explanations of networking concepts and packet flow.",
    url: "https://www.practicalnetworking.net/",
    access: "Free",
  },
  {
    id: "neso-oop",
    title: "Object-Oriented Programming",
    provider: "Neso Academy",
    platform: "Video lessons",
    category: "Core CS",
    topics: ["OOP", "Java", "classes", "polymorphism"],
    weeks: [20],
    description: "Video lessons on object-oriented programming fundamentals.",
    url: "https://www.youtube.com/@NesoAcademy",
    access: "Free",
  },
  {
    id: "java-tutorial",
    title: "The Java Tutorials",
    provider: "Oracle",
    platform: "Official documentation",
    category: "Java",
    topics: ["Java", "OOP", "collections", "exceptions"],
    weeks: [20],
    description: "Oracle’s Java tutorials covering language fundamentals and APIs.",
    url: "https://docs.oracle.com/javase/tutorial/",
    access: "Free",
  },
  {
    id: "gfg-software",
    title: "Software Engineering",
    provider: "GeeksforGeeks",
    platform: "Tutorial",
    category: "Core CS",
    topics: ["software engineering", "SDLC", "testing", "Git"],
    weeks: [21],
    description: "Software engineering concepts and interview preparation.",
    url: "https://www.geeksforgeeks.org/software-engineering/",
    access: "Free",
  },
  {
    id: "github-skills",
    title: "GitHub Skills",
    provider: "GitHub",
    platform: "Interactive tutorial",
    category: "Tools",
    topics: ["Git", "GitHub", "documentation", "projects"],
    weeks: [21, 29, 30, 31, 32],
    description: "Interactive courses for using GitHub through real repositories.",
    url: "https://skills.github.com/",
    access: "Free",
  },
  {
    id: "cisco-cyber",
    title: "Introduction to Cybersecurity",
    provider: "Cisco Networking Academy",
    platform: "Course",
    category: "Cybersecurity",
    topics: ["security principles", "threats", "network security"],
    weeks: [23, 24, 26, 27],
    description: "Introductory cybersecurity course from Cisco Networking Academy.",
    url: "https://skillsforall.com/course/introduction-to-cybersecurity",
    access: "Free",
  },
  {
    id: "tryhackme-presecurity",
    title: "Pre Security learning path",
    provider: "TryHackMe",
    platform: "Hands-on labs",
    category: "Cybersecurity",
    topics: ["security principles", "networking", "Linux"],
    weeks: [23],
    description: "Beginner learning path covering computer and security foundations.",
    url: "https://tryhackme.com/path/outline/presecurity",
    access: "Freemium",
  },
  {
    id: "owasp-top10",
    title: "OWASP Top 10",
    provider: "OWASP",
    platform: "Official documentation",
    category: "Cybersecurity",
    topics: ["web security", "OWASP", "application security"],
    weeks: [25, 39],
    description: "Awareness guide to common and important web application risks.",
    url: "https://owasp.org/www-project-top-ten/",
    access: "Free",
  },
  {
    id: "portswigger-academy",
    title: "Web Security Academy",
    provider: "PortSwigger",
    platform: "Hands-on labs",
    category: "Cybersecurity",
    topics: ["web security", "SQL injection", "XSS", "authentication"],
    weeks: [25],
    description: "Free interactive web-security learning materials and labs.",
    url: "https://portswigger.net/web-security",
    access: "Free",
  },
  {
    id: "tryhackme-web",
    title: "Web Fundamentals learning path",
    provider: "TryHackMe",
    platform: "Hands-on labs",
    category: "Cybersecurity",
    topics: ["web security", "OWASP", "authorized labs"],
    weeks: [25],
    description: "Beginner-friendly guided web-security practice.",
    url: "https://tryhackme.com/path/outline/web",
    access: "Freemium",
  },
  {
    id: "crypto101",
    title: "Crypto 101",
    provider: "Crypto 101",
    platform: "Book",
    category: "Cybersecurity",
    topics: ["cryptography", "encryption", "hashing", "signatures"],
    weeks: [26],
    description: "An introductory book on modern cryptography concepts.",
    url: "https://crypto101.io/",
    access: "Free",
  },
  {
    id: "neso-crypto",
    title: "Cryptography video lectures",
    provider: "Neso Academy",
    platform: "Video lessons",
    category: "Cybersecurity",
    topics: ["cryptography", "encryption", "hashing"],
    weeks: [26],
    description: "Video lessons introducing cryptographic ideas and terminology.",
    url: "https://www.youtube.com/@NesoAcademy",
    access: "Free",
  },
  {
    id: "tryhackme-soc",
    title: "SOC Level 1 learning path",
    provider: "TryHackMe",
    platform: "Hands-on labs",
    category: "Cybersecurity",
    topics: ["incident response", "logging", "SOC", "SIEM"],
    weeks: [27],
    description: "Guided SOC and alert-triage practice for beginners.",
    url: "https://tryhackme.com/path/outline/soclevel1",
    access: "Freemium",
  },
  {
    id: "aws-security",
    title: "AWS Security Documentation",
    provider: "Amazon Web Services",
    platform: "Official documentation",
    category: "Cloud security",
    topics: ["AWS", "IAM", "storage", "logging", "cloud security"],
    weeks: [28, 31, 32, 39],
    description: "Official security guidance across AWS identity, logging, and services.",
    url: "https://docs.aws.amazon.com/security/",
    access: "Free",
  },
  {
    id: "azure-security",
    title: "Describe security, compliance & identity concepts",
    provider: "Microsoft Learn",
    platform: "Course",
    category: "Cloud security",
    topics: ["Azure", "IAM", "cloud security", "shared responsibility"],
    weeks: [28, 31, 32, 39],
    description: "Microsoft Learn path for core cloud security and identity concepts.",
    url: "https://learn.microsoft.com/en-us/training/paths/describe-concepts-of-security-compliance-identity/",
    access: "Free",
  },
  {
    id: "markdown-guide",
    title: "The Markdown Guide",
    provider: "Markdown Guide",
    platform: "Documentation",
    category: "Tools",
    topics: ["README", "documentation", "portfolio"],
    weeks: [30, 32, 37],
    description: "A concise reference for writing useful Markdown documentation.",
    url: "https://www.markdownguide.org/",
    access: "Free",
  },
  {
    id: "indiabix",
    title: "Aptitude and reasoning practice",
    provider: "IndiaBIX",
    platform: "Practice platform",
    category: "Aptitude",
    topics: ["aptitude", "quantitative reasoning", "logical reasoning", "verbal"],
    weeks: [35],
    description: "Practice questions covering placement aptitude and reasoning topics.",
    url: "https://www.indiabix.com/",
    access: "Free",
  },
  {
    id: "cognizant-careers",
    title: "Cognizant Careers",
    provider: "Cognizant",
    platform: "Official company site",
    category: "Interview",
    topics: ["Cognizant", "GenC Next", "career research"],
    weeks: [37, 39, 40],
    description: "Official career information; check current role details and requirements.",
    url: "https://careers.cognizant.com/",
    access: "Free",
  },
];

export const resourceById = new Map(
  learningResources.map((resource) => [resource.id, resource]),
);

export const roadmapTopicCount = roadmapWeeks.reduce(
  (total, week) => total + week.topics.length,
  0,
);